### ISSUE TITLE
Load html triggers error -  resolve_url() missing 1 required positional argument: 'should_serve'

### ISSUE THREAD

**Issue by abhishekmishra** [r0x0r/pywebview#562]
### Specification
- pywebview version: 3.3.1
- platform / version: win10/64-bit, python 3.8.3

### Description  
  
Trying to load html in a pywebview window triggers an exception. Let me know if you need further info, I can also help with debugging.

Sample run (taken from examples in documentation)
```
window = webview.create_window('Load HTML Example', html='<h1>This is initial HTML</h1>')
```

Exception
```
Unhandled Exception: Python.Runtime.PythonException: TypeError : resolve_url() missing 1 required positional argument: 'should_serve'
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by lpanor** [comment]
I'm getting the same error! Spent 2 hours around this, thinking I was doing something wrong! :/ 

Thanks for posting the issue.

**Comment by sunilgoothy** [comment]
Same Error for me. I was trying multi-window example.

**Comment by lpanor** [comment]
> Same Error for me. I was trying multi-window example.
> Works fine if we use url parameter instead of html.

Yes, i can also use url with no problems for web urls (ex: google.com), but if I try to parse a local HTML ( C:\teste.html ) in the URL parameter i'm also getting an error. It's a diferent one and i'm still checking if it's note bad programing on my part, i don't think its related to this issue.

**Comment by r0x0r** [comment]
I pushed a fix to the master. Could someone verify it?

**Comment by bloemer** [comment]
Hi, I just copy and paste the script from the api's "load html example".
It's opening now without errors, but it displays "Path / was not found" (without quotes) and that's it.

**Comment by r0x0r** [comment]
I pushed a fix into the master. A throughout testing is needed and appreciated.

@astronouth7303 `bits.path` was empty for local URLs outside the application root, so I resorted to using `bits.netloc` if `path` is empty. Do you see any problem with this? It works at least on EdgeHTML (both for `load_html` and `http_server`). The commit in question is https://github.com/r0x0r/pywebview/commit/1c5a0500509ef4c84a8774bd9b4fe3ca32fdd093

**Comment by astronouth7303** [comment]
@r0x0r Added comments to the commit directly.

**Comment by r0x0r** [comment]
The latter commit fixes this issue. I am closing this issue and will release a new version soon.

**Comment by qaniere** [comment]
I have to re-open this issue because I have the issue. I paste the example from the documentation site, I try to put add empty URL, try to force cef GUI , I try to disable http_server, and it still don't work. I also try to load the google url then load html, the load html method has the same error as the html attribute : 

`Python.Runtime.PythonException: TypeError : resolve_url() missing 1 required positional argument: 'should_serve'      
   à Python.Runtime.Dispatcher.Dispatch(ArrayList args)
`

**Comment by r0x0r** [comment]
@qaniere Which example are you referring to? Are you using the latest version?

**Comment by qaniere** [comment]
It's strange, because the 3.3.3 version was producing the issue and I uninstall and install again pywebview and it seem to work even if pip logs tell me that is also the 3.3.3 version. Sorry for the inconvenience.
